compatibility_date = "2021-12-14"
name = "magical"
type = "webpack"
workers_dev = false
route = "magical.sh/*"
account_id = "f95121e2f529885dfc400497696f7761"
zone_id = "fbd80c9051d6975f20b9da9dbf580605"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "workers-site"